services:
  api:
    build: .
    container_name: eortologio-api
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - .:/app
    environment:
      - TZ=Europe/Athens
    restart: unless-stopped
